import React, { useState } from 'react';
import { X, Mail, Send, CheckCircle2, User, FileText, ExternalLink, Key, Check, Download } from 'lucide-react';
import type { CandidateProfile, ATSAnalysis, JobMatchResult } from '../types/resume';
import { USER_EMAIL_API_KEY, sendRealEmailViaAPI } from '../utils/emailService';
import { generatePDFReport } from '../utils/exportPdf';

interface EmailReportModalProps {
  profile: CandidateProfile;
  ats: ATSAnalysis;
  jobMatches: JobMatchResult[];
  onClose: () => void;
}

export const EmailReportModal: React.FC<EmailReportModalProps> = ({
  profile,
  ats,
  jobMatches,
  onClose
}) => {
  const topMatch = jobMatches[0];
  const finalResult = topMatch ? topMatch.finalResult : 'PASS (NEEDS IMPROVEMENT)';

  const [deliveryMethod, setDeliveryMethod] = useState<'api' | 'gmail' | 'mailto'>('api');
  const [recipientEmail, setRecipientEmail] = useState(profile.email || 'omthakkar168@gmail.com');
  const [emailSubject, setEmailSubject] = useState(`CAREERMATCH AI EVALUATION REPORT: ${profile.name.toUpperCase()} [${finalResult}]`);
  
  const fullAnalysisReportText = `=====================================================
CAREERMATCH AI - RESUME EVALUATION & ELIGIBILITY REPORT
=====================================================

1. CANDIDATE PROFILE METRICS
-----------------------------------------------------
• Candidate Name: ${profile.name}
• Professional Title: ${profile.title}
• Total Experience Level: ~${profile.experienceYears} Years
• Words Scanned in Resume: ${ats.totalWordsScanned} words
• Technical Keywords Extracted: ${ats.technicalSkillsCount} skills
• Extracted Skills Matrix: ${profile.skills.join(', ')}

2. ATS SCORE & KEYWORD AUDIT OVERALL SCORE: ${ats.overallScore} / 100
-----------------------------------------------------
• Technical Keyword Density: ${ats.keywordScore}%
• Section Formatting & Structure: ${ats.formattingScore}%
• Impact Verbs & Performance Metrics: ${ats.impactScore}%
• Contact Detail Completeness: ${ats.completenessScore}%

KEY STRENGTHS IDENTIFIED:
${ats.strengths.map(s => `- ${s}`).join('\n')}

ACTION ITEMS TO INCREASE ATS SCORE:
${ats.improvements.map(i => `- ${i}`).join('\n')}

3. COMPANY-SPECIFIC JOB ELIGIBILITY MATRIX
-----------------------------------------------------
${jobMatches.slice(0, 3).map((m, idx) => `
#${idx + 1} ${m.job.title} — ${m.job.company} (${m.matchPercentage}% Fit)
► ROLE DECISION: ${m.finalResult}
• Company Degree Requirement: ${m.job.minDegreeRequired || 'Bachelor Degree'}
• Experience Requirement: ${m.job.experienceYears}+ years
• Matching Skills: ${m.matchedSkills.join(', ')}
• Missing Skills to Learn: ${m.missingRequiredSkills.join(', ')}
`).join('\n')}

=====================================================
4. FINAL SELECTION RESULT FOR CANDIDATE: ${profile.name.toUpperCase()}
=====================================================
FINAL DECISION: ${finalResult}

EVALUATION SUMMARY:
Candidate ${profile.name} fulfills core foundational requirements. Company condition is favorable to hire/take candidate with targeted on-the-job improvement in missing skill modules.

-----------------------------------------------------
Report generated by CareerMatch AI Enterprise Platform.
College Submission & Enterprise Hiring Integration.
=====================================================`;

  const [emailBody, setEmailBody] = useState(fullAnalysisReportText);
  const [apiKey, setApiKey] = useState(USER_EMAIL_API_KEY);
  const [isSending, setIsSending] = useState(false);
  const [isSent, setIsSent] = useState(false);
  const [apiLogs, setApiLogs] = useState<string[]>([]);
  const [statusMessage, setStatusMessage] = useState('');

  const handleSendAPIEmail = async () => {
    setIsSending(true);
    const res = await sendRealEmailViaAPI({
      toEmail: recipientEmail,
      subject: emailSubject,
      body: emailBody,
      candidateName: profile.name,
      apiKey: apiKey
    });

    setIsSending(false);
    setIsSent(true);
    setApiLogs(res.logs);
    setStatusMessage(res.message);
  };

  const handleOpenGmailWeb = () => {
    const gmailUrl = `https://mail.google.com/mail/?view=cm&fs=1&to=${encodeURIComponent(recipientEmail)}&su=${encodeURIComponent(emailSubject)}&body=${encodeURIComponent(emailBody)}`;
    window.open(gmailUrl, '_blank');
    setIsSent(true);
    setStatusMessage(`Opened Gmail Web composer with full resume analysis report for ${recipientEmail}. Click "Send" in Gmail to deliver!`);
    setApiLogs([`[Gmail Web] Draft composer opened for ${recipientEmail}.`]);
  };

  const handleSendMailto = () => {
    const mailtoUrl = `mailto:${encodeURIComponent(recipientEmail)}?subject=${encodeURIComponent(emailSubject)}&body=${encodeURIComponent(emailBody)}`;
    window.location.href = mailtoUrl;
    setIsSent(true);
    setStatusMessage(`Opened native mail client for ${recipientEmail}.`);
    setApiLogs([`[Client App] Native mail client triggered for ${recipientEmail}.`]);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-md">
      <div className="glass-panel w-full max-w-2xl rounded-2xl border border-slate-800 p-6 sm:p-8 space-y-5 relative overflow-hidden shadow-2xl animate-in fade-in zoom-in duration-200 max-h-[90vh] overflow-y-auto">
        
        <button
          onClick={onClose}
          className="absolute top-4 right-4 p-2 text-slate-400 hover:text-white hover:bg-slate-800 rounded-full transition-colors"
        >
          <X className="w-5 h-5" />
        </button>

        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-purple-500/20 text-purple-400 flex items-center justify-center border border-purple-500/30">
            <Mail className="w-5 h-5" />
          </div>
          <div>
            <h3 className="text-lg font-bold text-white flex items-center gap-2">
              Email Candidate Evaluation Report
            </h3>
            <p className="text-xs text-slate-400">
              Dispatches full resume analysis & single-page PDF report.
            </p>
          </div>
        </div>

        <div className="grid grid-cols-3 gap-1.5 bg-slate-900/80 p-1.5 rounded-xl border border-slate-800 text-xs">
          <button
            onClick={() => setDeliveryMethod('api')}
            className={`py-2 rounded-lg font-semibold transition-all text-center ${
              deliveryMethod === 'api'
                ? 'bg-purple-500 text-white font-bold shadow-md'
                : 'text-slate-400 hover:text-white'
            }`}
          >
            ⚡ Web Email API
          </button>
          <button
            onClick={() => setDeliveryMethod('gmail')}
            className={`py-2 rounded-lg font-semibold transition-all text-center ${
              deliveryMethod === 'gmail'
                ? 'bg-purple-500 text-white font-bold shadow-md'
                : 'text-slate-400 hover:text-white'
            }`}
          >
            ✉️ Gmail Web
          </button>
          <button
            onClick={() => setDeliveryMethod('mailto')}
            className={`py-2 rounded-lg font-semibold transition-all text-center ${
              deliveryMethod === 'mailto'
                ? 'bg-purple-500 text-white font-bold shadow-md'
                : 'text-slate-400 hover:text-white'
            }`}
          >
            💻 Native App
          </button>
        </div>

        <div className="p-3 bg-sky-500/10 border border-sky-500/30 rounded-xl flex items-center justify-between gap-3 text-xs">
          <div className="flex items-center gap-2">
            <Download className="w-4 h-4 text-sky-400 shrink-0" />
            <span className="text-slate-200">
              Download the single-page PDF report to attach with your email:
            </span>
          </div>
          <button
            onClick={() => generatePDFReport(profile, ats, jobMatches)}
            className="px-3 py-1.5 bg-sky-500 hover:bg-sky-400 text-slate-950 font-bold text-xs rounded-lg transition-colors shrink-0"
          >
            Download PDF
          </button>
        </div>

        {isSent ? (
          <div className="p-6 text-center space-y-4 bg-emerald-500/10 border border-emerald-500/30 rounded-2xl animate-in fade-in">
            <CheckCircle2 className="w-12 h-12 text-emerald-400 mx-auto animate-bounce" />
            <div>
              <h4 className="font-bold text-white text-base">Full Resume Analysis Report Dispatched!</h4>
              <p className="text-xs text-slate-300 mt-1">
                {statusMessage}
              </p>
            </div>

            <div className="p-3 bg-slate-900 border border-slate-800 rounded-xl text-left text-xs text-slate-300 space-y-1">
              <span className="font-bold text-sky-400 block">📌 Next Step:</span>
              <p>1. If you clicked <strong>ACTIVATE FORM</strong> in your Gmail activation email, all report emails now land directly in your inbox!</p>
              <p>2. You can also click <strong>"Open in Gmail Web"</strong> below to send the full analysis with 1 click from your Gmail account.</p>
            </div>
            
            {apiLogs.length > 0 && (
              <div className="p-3 bg-slate-900 border border-slate-800 rounded-xl text-left text-[11px] font-mono text-emerald-400 space-y-1">
                {apiLogs.map((log, idx) => (
                  <div key={idx}>{log}</div>
                ))}
              </div>
            )}

            <div className="pt-2 flex items-center justify-center gap-3">
              <button
                onClick={handleOpenGmailWeb}
                className="px-4 py-2 bg-sky-500 hover:bg-sky-400 text-slate-950 font-bold text-xs rounded-xl shadow-md transition-colors flex items-center gap-1.5"
              >
                <ExternalLink className="w-3.5 h-3.5" /> Open in Gmail Web
              </button>
              <button
                onClick={onClose}
                className="px-4 py-2 bg-slate-800 hover:bg-slate-700 text-white font-bold text-xs rounded-xl border border-slate-700"
              >
                Close Window
              </button>
            </div>
          </div>
        ) : (
          <div className="space-y-4">
            
            {deliveryMethod === 'api' && (
              <div className="p-3 bg-slate-900/90 border border-purple-500/40 rounded-xl flex items-center justify-between gap-2">
                <div className="flex items-center gap-2">
                  <Key className="w-4 h-4 text-amber-400 shrink-0" />
                  <div>
                    <span className="text-[10px] font-bold uppercase text-purple-400 block">
                      Active Email API Key Configured:
                    </span>
                    <input
                      type="text"
                      value={apiKey}
                      onChange={(e) => setApiKey(e.target.value)}
                      className="text-xs font-mono text-slate-200 bg-transparent border-b border-purple-500/40 focus:outline-none w-full"
                    />
                  </div>
                </div>
                <span className="flex items-center gap-1 text-[10px] text-emerald-400 font-bold bg-emerald-500/10 px-2 py-1 rounded border border-emerald-500/30 shrink-0">
                  <Check className="w-3 h-3" /> Ready
                </span>
              </div>
            )}

            <div className="space-y-1.5">
              <label className="text-xs font-semibold text-slate-300 flex items-center gap-1.5">
                <User className="w-3.5 h-3.5 text-sky-400" /> Recipient Email Address:
              </label>
              <input
                type="email"
                value={recipientEmail}
                onChange={(e) => setRecipientEmail(e.target.value)}
                placeholder="Enter recipient email (e.g. omthakkar168@gmail.com)..."
                className="w-full px-3 py-2 bg-slate-900 border border-slate-800 rounded-xl text-xs text-slate-100 placeholder-slate-500 focus:outline-none focus:border-purple-500 font-medium"
              />
            </div>

            <div className="space-y-1.5">
              <label className="text-xs font-semibold text-slate-300 flex items-center gap-1.5">
                <FileText className="w-3.5 h-3.5 text-indigo-400" /> Email Subject Line:
              </label>
              <input
                type="text"
                value={emailSubject}
                onChange={(e) => setEmailSubject(e.target.value)}
                className="w-full px-3 py-2 bg-slate-900 border border-slate-800 rounded-xl text-xs text-slate-100 focus:outline-none focus:border-purple-500"
              />
            </div>

            <div className="space-y-1.5">
              <div className="flex items-center justify-between">
                <label className="text-xs font-semibold text-slate-300">
                  Full Resume Analysis Report Content:
                </label>
                <span className="text-[10px] text-slate-400">Includes ATS Score & Company Matches</span>
              </div>
              <textarea
                value={emailBody}
                onChange={(e) => setEmailBody(e.target.value)}
                className="w-full h-44 p-3 bg-slate-900 border border-slate-800 rounded-xl text-xs text-slate-200 focus:outline-none focus:border-purple-500 font-mono leading-relaxed"
              />
            </div>

            <div className="flex items-center justify-between pt-2">
              <span className="text-[11px] text-slate-400">
                Decision: <strong className="text-amber-400">{finalResult}</strong>
              </span>

              {deliveryMethod === 'api' && (
                <button
                  onClick={handleSendAPIEmail}
                  disabled={isSending}
                  className="flex items-center gap-2 px-5 py-2.5 bg-gradient-to-r from-purple-500 to-indigo-500 hover:from-purple-400 hover:to-indigo-400 text-white font-bold text-xs rounded-xl shadow-lg transition-all"
                >
                  {isSending ? (
                    <>Sending Full Report...</>
                  ) : (
                    <><Send className="w-3.5 h-3.5" /> Send Full Analysis Report</>
                  )}
                </button>
              )}

              {deliveryMethod === 'gmail' && (
                <button
                  onClick={handleOpenGmailWeb}
                  className="flex items-center gap-2 px-5 py-2.5 bg-gradient-to-r from-sky-500 to-blue-500 hover:from-sky-400 hover:to-blue-400 text-slate-950 font-bold text-xs rounded-xl shadow-lg transition-all"
                >
                  <ExternalLink className="w-3.5 h-3.5" /> Open in Gmail & Send
                </button>
              )}

              {deliveryMethod === 'mailto' && (
                <button
                  onClick={handleSendMailto}
                  className="flex items-center gap-2 px-5 py-2.5 bg-gradient-to-r from-purple-500 to-indigo-500 hover:from-purple-400 hover:to-indigo-400 text-white font-bold text-xs rounded-xl shadow-lg transition-all"
                >
                  <ExternalLink className="w-3.5 h-3.5" /> Launch Desktop Mail App
                </button>
              )}
            </div>

          </div>
        )}

      </div>
    </div>
  );
};
